env:
 browser: true
 es2021: true
 node: true
extends:
 - eslint:recommended
 - plugin:react/recommended
 - plugin:@typescript-eslint/recommended
 - next/core-web-vitals
parser: '@typescript-eslint/parser'
parserOptions:
 ecmaFeatures:
  jsx: true
 ecmaVersion: latest
 sourceType: module
plugins:
 - react
 - '@typescript-eslint'
rules:
 {
  '@typescript-eslint/ban-ts-comment': 'warn',
  '@typescript-eslint/no-non-null-assertion': 'off',
  'no-case-declarations': 'off',
  react-hooks/exhaustive-deps: 'off'
 }
